### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by GeorvityLabs** [dnth/dl-android-hf-blogpost#7]
thanks for a detailed blog and this project here on github.

first I got 
`Error: Member not found: 'ImageCropper.cropImage'`. ,
I solved it by changing `ImageCropper().cropImage to ImageCropper.cropImage`

that fixed problems and allowed me to run the app on my device
but after running , when I click on sample 3 and click on the 'Count!' button , it doesn't give me any count , on inspecting my log i saw the following error 

`[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'int' is not a subtype of type 'String'`
![error1](https://user-images.githubusercontent.com/58555432/168951025-9d365bc7-9fee-4529-9691-f73a7134849a.png)

**Comment by GeorvityLabs** [comment]
hope you could suggest how to fix this issue.

**Comment by dnth** [comment]
Hi @GeorvityLabs, I have pushed an update few hours ago to fix this issue. 

https://github.com/dnth/flutter_microalgae/commit/b3da4ac8bc1aaa5cf59d2620cc85d99c3891900e

**Comment by GeorvityLabs** [comment]
@dnth I am using the updated code.
But am still getting that error.
I ran using vscode , this is what i'm seeing :
![same](https://user-images.githubusercontent.com/58555432/168967818-063fe8c9-b671-463d-8862-a406a77c8567.png)

**Comment by dnth** [comment]
I've changed line 88 in update code. Can you confirm if you're using the same code as I do?

https://github.com/dnth/flutter_microalgae/blob/54fec7ff2d2932e77cc1ed74f50bdc7f201aa7d2/lib/main.dart#L88

**Comment by GeorvityLabs** [comment]
![same2](https://user-images.githubusercontent.com/58555432/168968686-8aa7f008-4e26-4b15-ad98-ea13f94fb11a.png)

**Comment by GeorvityLabs** [comment]
on VSCode it was showing some exception in line 287
![currentissue](https://user-images.githubusercontent.com/58555432/168968942-b60a776a-a2fa-4ab1-b987-7682c8db4086.png)

**Comment by dnth** [comment]
I see.. the fix is quite simple. Just change this line to

`_microalgaeCount = result['count'].toString();`

I've also update the codes in the repo. Let me know if it works.

**Comment by GeorvityLabs** [comment]
yup , that fixes the issue! @dnth
